### ISSUE TITLE
STDF_Reader_GUI 

### ISSUE THREAD

**Issue by drotshil** [showjim/STDFReader#3]
I have downloaded STDFReader-master and tried to run the STDF_Reader_GUI  but it is not working. pls advise.

**Comment by showjim** [comment]
Hi drotshil，
Could you describe what kind of issue you had encountered? If possible, can you share the app.log?

**Comment by drotshil** [comment]
Hi showjim, just click on the STDF_Reader_Gui python script and it is opening kind of cmd window then immediately closed.

**Comment by showjim** [comment]
It looks like you had not setup the environment correctly. If you would like to read the code, you can use an IDE or just a text editor. If you want to play with STDF files, you can download the EXE version from "release" page.

**Comment by drotshil** [comment]
I downloaded the EXE version from the release page but when trying to open it it pops up the following message: 
"This app can't run on your pc, to find a version for your pc check with the software publisher"

**Comment by showjim** [comment]
Since I build the EXE with pyinstaller, so you may need to turn off anti-virus software, like Defender...
ref: https://answers.microsoft.com/en-us/windows/forum/all/this-app-cant-run-on-your-pc-find-a-version-for/bdf25a36-51cd-424c-b079-2f03d164e2f7

**Comment by drotshil** [comment]
Hi, I was able to unzip the run the EXE version and I reached the point when it was able to open the dashboard window. however, when I tried to open STDF file and parse it didn't work for me. I didn't get any notification.

**Comment by drotshil** [comment]
Hi showjim, eventually I was able to parse single STDF file but it took me few minutes (for several STDFs will probably take much longer) and the output is a bit problematic as the columns/variables are shifted vs the rows. I also tried to use the #2 step option and analyze the data but the GUI crashed. Attached is the STDF file I used and the CSV output file I received.
[STDF example.zip](https://github.com/showjim/STDFReader/files/11016351/STDF.example.zip)

**Comment by showjim** [comment]
[STDF_report_sample.xlsx.zip](https://github.com/showjim/STDFReader/files/11017462/STDF_report_sample.xlsx.zip)

**Comment by showjim** [comment]
1. I have noticed it, and this is because the PART ID in PRR is missing from your sample STDF, which this tool is based on to count the DUT in each Bin.
2. Good advise, I will add one more col in analysis report in next version, maybe Beta V0.7.3;
3. This feature ha的been provided, but there are just too many Bin color scenario and I have no way to be compatible with all the possibilities. You can change it in the function **_generate_analysis_report_**, I have written some preset bin.
4. Yes and done, it seems that your work is similar to PE, currently this tool has provided the cumulative wafer map for 2 (please refer to README Step6); and I do not know how to make it more appropriate readable when wafer maps are greater than 3.
5. maybe in next version, or you can take advantage of Excel currently; you could find the fail rate for each bin per site in Bin Summary if the PART ID is not missing.
6. maybe in next version, or you can take advantage of Excel currently;

**Comment by drotshil** [comment]
Actually all of the above analysis I can do and doing in JMP software. Your tool is very nice but not the powerful as JMP. I guess the advantage of your Tool is that it is Free 😊, I will try playing with it a bit more. I think it has a lot of potential especially for engineers that have no access to industry tools such as JMP, SpotFire etc..

**Comment by showjim** [comment]
This tool is developed to help TE do the correlation work between different sites, DIBs, platforms, so I am not going to replace JMP, PDF or Galaxy(especially the STDF parse speed), but to improve efficiency of TE's work.
Welcome, you are the first person in the Issue section! If you find any other bugs need to be fixed or features that you want to add, please let me know.
